### PR TITLE
RFSwitchUtils: update antenna assignment

### PR DESCRIPTION
**Pull request by daniestevez**
Update for new wiring of the IF switch.

### CODE REVIEW

**Comment by daniestevez** [comment]
This still needs to be tested.

**Comment by wfarah** [comment]
Thanks, Danni. I'll leave the pull request open for now until we know the allocations are right

**Comment by daniestevez** [comment]
Marking this as ready. I completely forgot about this PR. At least `1a` is working with these changes, which is what we normally use with GNU Radio. I haven't tested any of the other antennas, but I expect them to work (and if there are some mistakes, another PR can be done). This PR matches the software that is currently installed.

**Comment by wfarah** [comment]
Excellent, thanks Danni!

**Pull request merged**
